### ISSUE TITLE
generete .npz file

### ISSUE THREAD

**Issue by Andreababy** [AlexiaJM/relativistic-f-divergences#6]
### **i change the dataset, i want to generate .npz file, i run create_FID_stats.py, some question  occures:*
  Traceback (most recent call last):
  File "create_FID_stats.py", line 49, in <module>
    mu, sigma = fid.calculate_activation_statistics_from_files(image_list, sess, batch_size=param.batch_size)
  File "/home/omnisky/project/relativistic-f-divergences-master/fid_new.py", line 247, in calculate_activation_statistics_from_files
    act = get_activations_from_files(files, sess, batch_size, verbose)
  File "/home/omnisky/project/relativistic-f-divergences-master/fid_new.py", line 216, in get_activations_from_files
    n_batches = d0//batch_size
 
Traceback (most recent call last):
  File "create_FID_stats.py", line 49, in <module>
    mu, sigma = fid.calculate_activation_statistics_from_files(image_list, sess, batch_size=param.batch_size)
  File "/home/omnisky/project/relativistic-f-divergences-master/fid_new.py", line 247, in calculate_activation_statistics_from_files
    act = get_activations_from_files(files, sess, batch_size, verbose)
  File "/home/omnisky/project/relativistic-f-divergences-master/fid_new.py", line 216, in get_activations_from_files
    n_batches = d0//batch_size
ZeroDivisionError: integer division or modulo by zero

 **Can you tell me how to generate? Is there any command for my own dataset? Thank you**

**Comment by AlexiaJM** [comment]
See the end of https://github.com/AlexiaJM/relativistic-f-divergences/blob/master/setting_up_script.sh which gives examples of these being created.
